### ISSUE TITLE
Return an error when lampo-wallet already exists

### ISSUE THREAD

**Issue by Harshit933** [vincenzopalazzo/lampo.rs#296] opened 2024-11-02 07:49 UTC
Return the error when creating a new wallet while an old wallet already exists.

See comment https://github.com/vincenzopalazzo/lampo.rs/issues/233#issuecomment-2152618068 and https://github.com/vincenzopalazzo/lampo.rs/issues/233#issuecomment-2152661039

**Comment by vincenzopalazzo** [comment] 2024-11-02 10:30
@Psycho-Pirate is working on this with https://github.com/vincenzopalazzo/lampo.rs/pull/295

**Comment by vincenzopalazzo** [comment] 2024-12-06 08:16
@Harshit933 Do you think that this is fixed? can you double check? and closing the issue fi yes

**Comment by vincenzopalazzo** [comment] 2024-12-06 21:45
The issue is describing

>Return the error when creating a new wallet while an old wallet already exists.

So probably this is already solved right?

**Comment by vincenzopalazzo** [comment] 2024-12-06 21:46
>After creating a fresh new wallet I deleted it, then after if I put money on my bitcoin wallet via bitcoin-cli

This is an invalid operation, so probably you mean creating a new wallet in bitcoin core? and not a lampo wallet?

**Comment by Harshit933** [comment] 2024-12-07 08:31
> This is an invalid operation, so probably you mean creating a new wallet in bitcoin core? and not a lampo wallet?

When we create a new wallet in lampo, it esentially resides in `.bitcoin/<network>` and we communicate to that wallet via `bitcoincore_rpc` we can also communicate to that wallet via `bitcoin-cli`, which is what I did here.

> So probably this is already solved right?

Yup, this issue is resolved, if we think that the user have not deleted the `.lampo` directory, which is an invalid operation.

**Comment by vincenzopalazzo** [comment] 2024-12-07 08:35
>if we think that the user have not deleted the .lampo directory, which is an invalid operation

Right it is, why someone should delete a wallet :) well it is also true that people do crazy stuff. Let see if we can improve this somehow

**Closed by vincenzopalazzo** 2024-12-07 08:35 UTC
Labels: P-medium
