### ISSUE TITLE
lampod socket gets deleted while using lampo

### ISSUE THREAD

**Issue by Harshit933** [vincenzopalazzo/lampo.rs#184] opened 2024-02-05 10:11 UTC
When I am trying to operate lampo. `lampod.socket` inside `.lampo/signet/` gets automaitcally deleted.

The `lampo-cli` works for some time then gets me this error. :
```
harshit@harshit:~$ lampo-cli --network testnet getinfo
{
  "node_id": "023f43f9c52dc45a0de49b32980c600b2dae3b7f1a36a4b494349287058a541ad7",
  "peers": 0,
  "channels": 0
}
harshit@harshit:~$ lampo-cli --network testnet getinfo
✗ JSON decode error: Connection reset by peer (os error 104)
```
```
harshit@harshit:~$ lampo-cli --network signet getinfo
{
  "node_id": "0307aeab70d7a9d9e498ebf421144e1bbbd4d6345443c25b9a2a28e3d5fd23161e",
  "peers": 0,
  "channels": 0
}
harshit@harshit:~$ lampo-cli --network signet getinfo
✗ JSON decode error: Broken pipe (os error 32)
```
```
harshit@harshit:~$ lampo-cli --network signet getinfo
✗ JSON decode error: Connection reset by peer (os error 104)
harshit@harshit:~$ lampo-cli --network signet getinfo
✗ IO error response: No such file or directory (os error 2)
harshit@harshit:~$ lampo-cli --network signet getinfo
harshit@harshit:~$ lampo-cli --network signet getinfo
✗ IO error response: Connection refused (os error 111)
```
These are the logs : 
```
2024-02-03T11:38:41.393Z TRACE jsonrpc new connection to unix rpc socket. [lampo-jsonrpc/src/lib.rs:197]
2024-02-03T11:38:41.393Z INFO jsonrpc blocking with err Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }!. [lampo-jsonrpc/src/lib.rs:225]
2024-02-03T11:38:41.393Z INFO jsonrpc buffer read {"method":"getinfo","params":{},"id":"0","jsonrpc". [lampo-jsonrpc/src/lib.rs:232]
2024-02-03T11:38:46.597Z TRACE ldk lightning_background_processor:785 TRACE Calling PeerManager's timer_tick_occurred. [lampod/src/utils/logger.rs:50]
```
```
2024-02-03T11:53:08.915Z INFO jsonrpc buffer read {"method":"getinfo","params":. [lampo-jsonrpc/src/lib.rs:232]
2024-02-03T11:53:16.570Z TRACE ldk lightning_background_processor:785 TRACE Calling PeerManager's timer_tick_occurred. [lampod/src/utils/logger.rs:50]
2024-02-03T11:53:27.605Z TRACE ldk lightning_background_processor:785 TRACE Calling PeerManager's timer_tick_occurred. [lampod/src/utils/logger.rs:50]
2024-02-03T11:53:36.520Z TRACE ldk lightning_background_processor:785 TRACE Rebroadcasting monitor's pending claims. [lampod/src/utils/logger.rs:50]
2024-02-03T11:53:38.624Z TRACE ldk lightning_background_processor:785 TRACE Calling PeerManager's timer_tick_occurred. [lampod/src/utils/logger.rs:50]
2024-02-03T11:53:49.645Z TRACE ldk lightning_background_processor:785 TRACE Calling PeerManager's timer_tick_occurred. [lampod/src/utils/logger.rs:50]
2024-02-03T11:54:00.663Z TRACE ldk lightning_background_processor:785 TRACE Calling PeerManager's timer_tick_occurred. [lampod/src/utils/logger.rs:50]
2024-02-03T11:54:05.485Z TRACE lampo_bitcoind Current Status during another iteration BitcoinCore { best_height: RefCell { value: 180985 }, last_bloch_hash: RefCell { value: Some(00000051df9f44dc1a8d710eed159579a8837f7dfa1ee0c2ca15b3d6f42889b5) } }. [lampo-bitcoind/src/lib.rs:423]
```
Laptop model : HP Pavilion Notebook
My OS  : Ubuntu 22.04 LTS
Architecture:           x86_64
  CPU op-mode(s):       32-bit, 64-bit
  Address sizes:        39 bits physical, 48 bits virtual
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              GenuineIntel
  Model name:           Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    CPU family:         6
    Model:              78
    Thread(s) per core: 2
    Core(s) per socket: 2
    Socket(s):          1
    Stepping:           3

**Comment by vincenzopalazzo** [comment] 2024-03-19 09:59
I am not able to reproduce it, are you now?

**Comment by vincenzopalazzo** [comment] 2024-03-30 14:37
closing fro missing feedback

**Closed by vincenzopalazzo** 2024-03-30 14:37 UTC
Labels: help wanted, P-waiting, 🌨️ - blocked
